/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erpvistas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *Ventana del Administrador.
 * @author fabio, Arnold, Jordy, Gladys
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Dashboard
     */
    double caja;
    double abrirCaja;
    double cerrarCaja;
    double venta;

    public Admin_Dashboard() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        makeOrder = new javax.swing.JButton();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        makeOrder2 = new javax.swing.JButton();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        makeOrder3 = new javax.swing.JButton();
        jInternalFrame8 = new javax.swing.JInternalFrame();
        makeOrder4 = new javax.swing.JButton();
        jInternalFrame9 = new javax.swing.JInternalFrame();
        makeOrder5 = new javax.swing.JButton();
        jInternalFrame10 = new javax.swing.JInternalFrame();
        makeOrder6 = new javax.swing.JButton();
        jInternalFrame11 = new javax.swing.JInternalFrame();
        makeOrder7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jInternalFrame12 = new javax.swing.JInternalFrame();
        makeOrder8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        inventario = new javax.swing.JMenuItem();
        mesa = new javax.swing.JMenuItem();
        signOff = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        cashClosing = new javax.swing.JMenuItem();
        modMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Punto de Venta Administrador");

        jInternalFrame4.setVisible(true);

        makeOrder.setText("Crear Pedido");
        makeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeOrderMouseClicked(evt);
            }
        });
        makeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame6.setVisible(true);

        makeOrder2.setText("Crear Pedido");
        makeOrder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder2)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame7.setVisible(true);

        makeOrder3.setText("Crear Pedido");
        makeOrder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder3)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame8.setVisible(true);

        makeOrder4.setText("Crear Pedido");
        makeOrder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame8Layout = new javax.swing.GroupLayout(jInternalFrame8.getContentPane());
        jInternalFrame8.getContentPane().setLayout(jInternalFrame8Layout);
        jInternalFrame8Layout.setHorizontalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame8Layout.setVerticalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder4)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame9.setVisible(true);

        makeOrder5.setText("Crear Pedido");
        makeOrder5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame9Layout = new javax.swing.GroupLayout(jInternalFrame9.getContentPane());
        jInternalFrame9.getContentPane().setLayout(jInternalFrame9Layout);
        jInternalFrame9Layout.setHorizontalGroup(
            jInternalFrame9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame9Layout.setVerticalGroup(
            jInternalFrame9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder5)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame10.setVisible(true);

        makeOrder6.setText("Crear Pedido");
        makeOrder6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame10Layout = new javax.swing.GroupLayout(jInternalFrame10.getContentPane());
        jInternalFrame10.getContentPane().setLayout(jInternalFrame10Layout);
        jInternalFrame10Layout.setHorizontalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame10Layout.setVerticalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder6)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jInternalFrame11.setVisible(true);

        makeOrder7.setText("Crear Pedido");
        makeOrder7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame11Layout = new javax.swing.GroupLayout(jInternalFrame11.getContentPane());
        jInternalFrame11.getContentPane().setLayout(jInternalFrame11Layout);
        jInternalFrame11Layout.setHorizontalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame11Layout.setVerticalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder7)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jButton1.setText("Facturar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jInternalFrame12.setVisible(true);

        makeOrder8.setText("Crear Pedido");
        makeOrder8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeOrder8MouseClicked(evt);
            }
        });
        makeOrder8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame12Layout = new javax.swing.GroupLayout(jInternalFrame12.getContentPane());
        jInternalFrame12.getContentPane().setLayout(jInternalFrame12Layout);
        jInternalFrame12Layout.setHorizontalGroup(
            jInternalFrame12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeOrder8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame12Layout.setVerticalGroup(
            jInternalFrame12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(makeOrder8)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        inicio.setText("Inicio");

        inventario.setText("Inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        inicio.add(inventario);

        mesa.setText("Crear Mesa");
        mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaActionPerformed(evt);
            }
        });
        inicio.add(mesa);

        signOff.setText("Cerrar Sesion");
        signOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOffActionPerformed(evt);
            }
        });
        inicio.add(signOff);

        jMenuItem1.setText("Abrir Caja");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        inicio.add(jMenuItem1);

        cashClosing.setText("Cerrar Caja");
        cashClosing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashClosingMouseClicked(evt);
            }
        });
        cashClosing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashClosingActionPerformed(evt);
            }
        });
        inicio.add(cashClosing);

        modMenu.setText("Agregar platos al menú");
        modMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modMenuActionPerformed(evt);
            }
        });
        inicio.add(modMenu);

        jMenuBar1.add(inicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFrame12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jInternalFrame10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFrame8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jInternalFrame9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInternalFrame4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jInternalFrame12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        // TODO add your handling code here:
        /**
         * Se muestra la ventana del inventario para agregar productos,
         * eliminarlos modicar precios y ver las existencias.
         *
         */
        Inventory_Dashboard inventario = new Inventory_Dashboard();
        inventario.setVisible(true);

    }//GEN-LAST:event_inventarioActionPerformed

    private void mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaActionPerformed

    private void signOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOffActionPerformed
        // TODO add your handling code here:
        //*  Nos devuelve al Login */ 

        Login log = new Login();

        log.setVisible(true);

        dispose();
    }//GEN-LAST:event_signOffActionPerformed
//Debe mostrar la ventana con el menú para agregar productos
    private void makeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_makeOrderActionPerformed

    private void makeOrder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder3ActionPerformed
        Order_Dashboard order3 = new Order_Dashboard();
        order3.setVisible(true);
    }//GEN-LAST:event_makeOrder3ActionPerformed

    private void makeOrder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder2ActionPerformed
        Order_Dashboard order4 = new Order_Dashboard();
        order4.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_makeOrder2ActionPerformed

    private void makeOrder6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder6ActionPerformed
        Order_Dashboard order5 = new Order_Dashboard();
        order5.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_makeOrder6ActionPerformed

    private void makeOrder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder4ActionPerformed
        Order_Dashboard order6 = new Order_Dashboard();
        order6.setVisible(true);
    }//GEN-LAST:event_makeOrder4ActionPerformed

    private void makeOrder5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder5ActionPerformed
        Order_Dashboard order7 = new Order_Dashboard();
        order7.setVisible(true);
    }//GEN-LAST:event_makeOrder5ActionPerformed

    private void makeOrder7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder7ActionPerformed
        Order_Dashboard order8 = new Order_Dashboard();
        order8.setVisible(true);

    }//GEN-LAST:event_makeOrder7ActionPerformed

    private void cashClosingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashClosingActionPerformed

    }//GEN-LAST:event_cashClosingActionPerformed

    private void modMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modMenuActionPerformed
        AddMenu añadirMenu = new AddMenu();

        añadirMenu.setVisible(true);


    }//GEN-LAST:event_modMenuActionPerformed

    private void makeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeOrderMouseClicked
        Order_Dashboard order1 = new Order_Dashboard();
        order1.setVisible(true);
    }//GEN-LAST:event_makeOrderMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        double venta = 0;
        double abrirCaja = 10000;

        JOptionPane.showMessageDialog(null, "Caja abierta con exito");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked


    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void cashClosingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashClosingMouseClicked

        double cerrarCaja = venta - abrirCaja;

    }//GEN-LAST:event_cashClosingMouseClicked


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        /**
         * Solicita al usuario el número de mesa para facturar y muestra el
         * total de la factura. Si el archivo de la mesa existe, se calcula el
         * total de la factura llamando al método
         * {@link #calculateInvoice(String)}. Si el archivo no existe, se
         * muestra un mensaje de error.
         */

        String orderToInvoice = JOptionPane.showInputDialog(null, "Digite el número de mesa que desea facturar");

        String numTable = "Mesa " + orderToInvoice + ".txt";

        File table = new File(numTable);
        if (table.exists()) {
            double totalInvoice = calculeInvoice(numTable);

            // Acciones adicionales de facturación, como imprimir o mostrar el total en una interfaz de usuario
            JOptionPane.showMessageDialog(null, "Total de la factura para la mesa " + orderToInvoice + ":  ₡" + totalInvoice);
            try (BufferedReader br = new BufferedReader(new FileReader(table))) {
                String linea;
                LocalDate date= LocalDate.now();
                System.out.println(date);
                while ((linea = br.readLine()) != null) {
                    
                    System.out.println("Plato  " + "Precio  " + "Cantidad");
                    System.out.println(linea);

                }
                System.out.println("Total sin Iva" + "₡" + totalInvoice);
                System.out.println("IVA    13%");
                System.out.println("Total con Iva   ₡ " + (totalInvoice + totalInvoice * 0.13));
            } catch (IOException e) {
                System.out.println("Error al leer el archivo: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el archivo para la mesa " + orderToInvoice);
        }
    }

    /**
     * Calcula el total de la factura leyendo el table especificado.
     *
     * @param nombreArchivo el nombre del table que contiene los datos de la
     * factura.
     * @return el total de la factura.
     */
    private double calculeInvoice(String nombreArchivo) {
        double total = 0.0;

        try (BufferedReader br = new BufferedReader(new FileReader(nombreArchivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length >= 2) {
                    double precio = Double.parseDouble(datos[1].trim());
                    if (datos.length >= 3) {
                        int cantidad = Integer.parseInt(datos[2].trim());
                        total += precio * cantidad;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al calcular el total de la factura" + e.getMessage());

        }

        return total;


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void makeOrder8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeOrder8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_makeOrder8MouseClicked

    private void makeOrder8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeOrder8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cashClosing;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenuItem inventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame10;
    private javax.swing.JInternalFrame jInternalFrame11;
    private javax.swing.JInternalFrame jInternalFrame12;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JInternalFrame jInternalFrame8;
    private javax.swing.JInternalFrame jInternalFrame9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton makeOrder;
    private javax.swing.JButton makeOrder2;
    private javax.swing.JButton makeOrder3;
    private javax.swing.JButton makeOrder4;
    private javax.swing.JButton makeOrder5;
    private javax.swing.JButton makeOrder6;
    private javax.swing.JButton makeOrder7;
    private javax.swing.JButton makeOrder8;
    private javax.swing.JMenuItem mesa;
    private javax.swing.JMenuItem modMenu;
    private javax.swing.JMenuItem signOff;
    // End of variables declaration//GEN-END:variables
}
