/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erpvistas;

import inventario.Base_Inventario;
import inventario.Product;
import inventario.Tabla_Inventario;
import javax.swing.JOptionPane;

/**
 * Ventana principal para el panel de control del inventario. Permite agregar,
 * actualizar, eliminar y generar informes sobre productos. Esta ventana utiliza
 * la clase Base_Inventario y la clase Tabla_Inventario. Autores: Arnold, Fabio,
 * Jordy, Gladys
 */
public class Inventory_Dashboard extends javax.swing.JFrame {

    public int codigo;
    public String nombre;
    public double precio;
    public int existencia;
    Product Producto[];
    Base_Inventario BI_Producto = new Base_Inventario();

    /**
     * Ventana principal para el panel de control del inventario. Permite
     * agregar, actualizar, eliminar y generar informes sobre productos. Esta
     * ventana utiliza la clase Base_Inventario y la clase Tabla_Inventario.
     * Autores: Arnold, Fabio, Jordy, Gladys
     */
    public Inventory_Dashboard() {
        initComponents();
        this.tblTabla.setModel(new Tabla_Inventario(BI_Producto.getLista()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGenerar_Informe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Inventario");

        jLabel2.setText("Codigo");

        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        jLabel5.setText("Existencia");

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGenerar_Informe.setText("Generar Informe");
        btnGenerar_Informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerar_InformeActionPerformed(evt);
            }
        });

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPrecio)
                                .addComponent(txtNombre)
                                .addComponent(txtCodigo)
                                .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(121, 121, 121)
                                .addComponent(btnEliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnGenerar_Informe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(btnGenerar_Informe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//---------------------------------------------------------------------------//
    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed
   /**
    * Método que se ejecuta al hacer clic en el botón "Agregar".
    * Realiza la validación de los datos ingresados y agrega un producto al inventario.
    * @param evt El evento de acción que desencadena la ejecución del método.
    */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
          /**
        * Realiza la validación de los datos ingresados y agrega un producto al inventario si los datos son válidos.
        * Muestra mensajes de advertencia o éxito según corresponda.
        */
      if(validar()){
            if(!BI_Producto.verificarExistencia(nombre)){
                // Generar un nuevo código para el producto
                if(codigo == 0){
                    // Crear un nuevo producto con los datos ingresados
                    int codigoAux = BI_Producto.ultimoCodigo() + 1;
                    // Agregar el producto al inventario
                    BI_Producto.agregar(new Product(codigoAux, nombre, precio, existencia));
                    // Actualizar la tabla en la interfaz de usuario con la lista actualizada de producto
                    this.tblTabla.setModel(new Tabla_Inventario(BI_Producto.getLista()));
                    // Limpiar los datos ingresados en la interfaz de usuario
                    limpiarDatos();
                     // Mostrar un mensaje de éxito indicando que el producto ha sido agregado
                     JOptionPane.showMessageDialog(this, "Producto agregado","AGREGADO", 1);
                }else{
                    // Mostrar un mensaje de advertencia indicando que se ha ingresado un código de línea
                    JOptionPane.showMessageDialog(this, "ADVERTENCIA DE LINEA CODIGO","ADVERTENCIA",2);
                }
            }else{
                // Mostrar un mensaje de advertencia indicando que el producto ya existe en el inventario
                JOptionPane.showMessageDialog(this, "ADVERTENCIA DE LINEA VERIFICAR EXISTENCIA","ADVERTENCIA",2); 
            }
        }else{
            // Mostrar un mensaje de advertencia indicando que los datos ingresados no son válidos
            JOptionPane.showMessageDialog(this, "ADVERTENCIA DE LINEA VALIDAR","ADVERTENCIA",2);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void tblTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaMouseClicked
        // TODO add your handling code here:
        Product producto = ((Tabla_Inventario) this.tblTabla.getModel())
                .detalle(this.tblTabla.getSelectedRow());
        this.txtCodigo.setText(String.valueOf(producto.getCodigo()));
        this.txtNombre.setText(producto.getNombre());
        this.txtPrecio.setText(String.valueOf(producto.getPrecio()));
        this.txtExistencia.setText(String.valueOf(producto.getExistencia()));

    }//GEN-LAST:event_tblTablaMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (validar()) {
            BI_Producto.actualizar(new Product(codigo, nombre, precio, existencia));
            this.tblTabla.setModel(new Tabla_Inventario(BI_Producto.getLista()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Actualizado exitosamente", "ACTUALIZADO", 1);
        } else {
            JOptionPane.showMessageDialog(this, "ADVERTENCIA DE ACTUALIZACION", "ADVERTENCIA", 2);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (validar()) {
            BI_Producto.eliminar(new Product(codigo, nombre, precio, existencia));
            this.tblTabla.setModel(new Tabla_Inventario(BI_Producto.getLista()));
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "Eliminado exitosamente", "ACTUALIZADO", 1);
        } else {
            JOptionPane.showMessageDialog(this, "ADVERTENCIA DE ELIMINACION", "ADVERTENCIA", 2);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGenerar_InformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerar_InformeActionPerformed
//        Base_Inventario inventario = new Base_Inventario();
//        inventario.verificarExistenciaBaja();
//        JOptionPane.showMessageDialog(this, inventario.verificarExistenciaBaja(),"ADVERTENCIA" ,2);
        Base_Inventario inventario = new Base_Inventario();
        inventario.verificarExistenciaBaja();
    }//GEN-LAST:event_btnGenerar_InformeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowClosed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
/**
        * Valida los datos ingresados en los campos de texto de la interfaz de usuario.
        * @return true si los datos son válidos, false si hay algún error.
        */
        public boolean validar(){
            try{
                // Validar el código
                codigo = Integer.parseInt("".equals(txtCodigo.getText())? "0" 
                        : txtCodigo.getText());
                // Validar el nombre
                nombre = txtNombre.getText();
                // Validar el precio
                precio = Double.parseDouble(txtPrecio.getText());
                // Validar la existencia
                existencia = Integer.parseInt(txtExistencia.getText()); 
                // Todos los datos son válidos
                return true;
            }
            catch(Exception e){
                // Hubo un error al convertir los datos o algún campo está vacío
                return false;
            }
        }
        /**
        * Limpia los campos de texto en la interfaz de usuario.
        */
        public void limpiarDatos(){
            this.txtCodigo.setText("");
            this.txtNombre.setText("");
            this.txtPrecio.setText("");
            this.txtExistencia.setText("");
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar_Informe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
