/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erpvistas;

import java.awt.TextField;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;


/**
 *Ventana que permite realizar la orden de cada mesa.
 * @author Arnold, Fabio, GLadys, Jordy
 */
public class Order_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Order_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        JCBarrozConPollo = new javax.swing.JCheckBox();
        JCBcasado = new javax.swing.JCheckBox();
        JCBgalloPinto = new javax.swing.JCheckBox();
        btnGenerar_Pedido = new javax.swing.JButton();
        arrozConPolloCantidad = new javax.swing.JLabel();
        casadoCantidad = new javax.swing.JLabel();
        galloPintoCantidad = new javax.swing.JLabel();
        arrozConPollo = new javax.swing.JTextField();
        casado = new javax.swing.JTextField();
        galloPinto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numMesa = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JCBarrozConPollo.setText("Arroz Con Pollo  1200");
        JCBarrozConPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBarrozConPolloActionPerformed(evt);
            }
        });

        JCBcasado.setText("Casado,1200");
        JCBcasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBcasadoActionPerformed(evt);
            }
        });

        JCBgalloPinto.setText("Gallo Pinto,1200");
        JCBgalloPinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBgalloPintoActionPerformed(evt);
            }
        });

        btnGenerar_Pedido.setText("Generar Pedido");
        btnGenerar_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerar_PedidoActionPerformed(evt);
            }
        });

        arrozConPolloCantidad.setText("Cantidad:");

        casadoCantidad.setText("Cantidad:");

        galloPintoCantidad.setText("Cantidad:");

        arrozConPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrozConPolloActionPerformed(evt);
            }
        });

        galloPinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galloPintoActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Mesa");

        numMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(galloPintoCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(galloPinto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casadoCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(casado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBarrozConPollo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(arrozConPolloCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arrozConPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JCBcasado, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBgalloPinto, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnGenerar_Pedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(JCBarrozConPollo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrozConPolloCantidad)
                    .addComponent(arrozConPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JCBcasado)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casadoCantidad)
                    .addComponent(casado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(JCBgalloPinto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(galloPintoCantidad)
                    .addComponent(galloPinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(btnGenerar_Pedido)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerar_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerar_PedidoActionPerformed
        
        String cantidadArrozConPollo= arrozConPolloCantidad.getText();
        String cantidadCasado= casadoCantidad.getText();
        String cantidadPinto= galloPintoCantidad.getText();
        String numMesa = this.numMesa.getText();
        try {
        PrintWriter writer = new PrintWriter(new FileWriter("Mesa "+numMesa+".txt"));
        
        //File pedido = new File ("nuevo pedido.txt");

    // Verifica si cada checkbox está seleccionado y escribe la opción correspondiente en el archivo
            if (JCBarrozConPollo.isSelected()) {
                writer.println(JCBarrozConPollo.getText()+ ","+ arrozConPollo.getText());
                
            }
            if (JCBcasado.isSelected()) {
                writer.println(JCBcasado.getText() + "," + casado.getText());

            }
            if (JCBgalloPinto.isSelected()) {
                writer.println(JCBgalloPinto.getText()+ ","+ galloPinto.getText());

            }

            writer.close();
            JOptionPane.showMessageDialog(null,"Pedido generado correctamente para mesa" + numMesa);
            System.out.println("Pedido generado correctamente");
        } catch (IOException e) {
            System.out.println("Error al guardar el pedido" + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerar_PedidoActionPerformed

    private void JCBcasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBcasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBcasadoActionPerformed

    private void JCBarrozConPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBarrozConPolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBarrozConPolloActionPerformed

    private void JCBgalloPintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBgalloPintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBgalloPintoActionPerformed

    private void arrozConPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrozConPolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrozConPolloActionPerformed

    private void galloPintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galloPintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_galloPintoActionPerformed

    private void numMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMesaActionPerformed


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCBarrozConPollo;
    private javax.swing.JCheckBox JCBcasado;
    private javax.swing.JCheckBox JCBgalloPinto;
    private javax.swing.JTextField arrozConPollo;
    private javax.swing.JLabel arrozConPolloCantidad;
    private javax.swing.JButton btnGenerar_Pedido;
    private javax.swing.JTextField casado;
    private javax.swing.JLabel casadoCantidad;
    private javax.swing.JTextField galloPinto;
    private javax.swing.JLabel galloPintoCantidad;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numMesa;
    // End of variables declaration//GEN-END:variables
}
